### ISSUE TITLE
tsc ci failure

### ISSUE THREAD

**Issue by dcroote** [api3dao/promise-utils#186]
CI is failing in #185  with 
```
> @api3/promise-utils@0.4.0 lint:tsc /home/runner/work/promise-utils/promise-utils
> pnpm tsc -p .

Error: src/index.ts(169,75): error TS2550: Property 'at' does not exist on type 'number[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2022' or later.
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 2.
Error: Process completed with exit code 2.
```

It should be a simple change that doesn't require changing the target library and possibly affecting compatibility

**Comment by dcroote** [comment]
I'll create a PR (can't assign myself to the issue because it looks like I don't have permissions for this repo)

**Comment by matejfalat** [comment]
Package was migrated to api3dao/commons.
